### ISSUE TITLE
OMERO Images in viewer different from corresponding thumbnails 

### ISSUE THREAD

**Issue by tabusaqri** [ome/omero-insight#155] opened 2020-07-23 06:48 UTC
Hi Team,

We are facing a problem with OMERO uploaded images.  the images in the viewer are different from corresponding thumbnails. 

1- First we can see in the same folder different images have the same wrong thumbnail.
2- When we open the image in the image viewer we can see the correct image.

Can you please help us on this issue. 

Regards,
Tariq Abu Saqri

**Comment by dominikl** [comment] 2020-07-23 08:49
Does that happen right after the import or after changing the rendering settings? 
Do you use any specific import options (like "Skip min/max calculation" etc.)?
What happens if you change and save the rendering settings, do thumbnail and image show the same then?
Do you have OMERO.web installed too? Would be interesting how it looks there.
Sorry, lot of questions. Just trying to replicate the problem.

**Comment by tabusaqri** [comment] 2020-07-23 09:29
H Dominik,

1- It's after the import. But please note, we converted first the images using raw2ometiff-0.2.6 tool, then we import it. 
2- I'm not using andy options in the import. only the default option by OMERO.insigh.
3- Nothing will happen when we save the rendering. 
4- Yes, we are using OMER.web 5.5.1-ice36-b122.

Also, please note, when we zoom out the image to the minimum zoom, it will show the wrong image similar to the thumbnails. 

Please find the attached images for more clarification.

Regards,
Tariq Abu Saqri

![OMERO_image_issue_3](https://user-images.githubusercontent.com/45575899/88271575-03feeb00-cce0-11ea-8c57-b5f4926def71.png)
![OMERO_image_issue_2](https://user-images.githubusercontent.com/45575899/88271610-10834380-cce0-11ea-9b84-1758c03517dd.png)

**Comment by dominikl** [comment] 2020-07-23 10:21
Thanks for the info. Initially I thought that might be an issue with the rendering settings. But this rather looks like a problem with the data itself or the conversion to ome.tiff. Would you mind uploading an example file via http://qa.openmicroscopy.org.uk/qa/upload/ (if it's smaller than 2GB) ?

**Comment by tabusaqri** [comment] 2020-07-26 08:34
Thank you for sharing the upload link. I'm trying to do that but I can't open the window to upload an example image. Can you please let me know how to do that?  

Please see the image below for what I'm facing.

![Screen Shot 2020-07-26 at 9 09 45 AM](https://user-images.githubusercontent.com/45575899/88472847-fafc5c80-cf1f-11ea-8d69-084dae98e50d.png)

**Comment by joshmoore** [comment] 2020-07-27 08:50
Hi @tabusaqri. If you are having troubles sending via QA, it might be easiest to either put the files somewhere for us to download (dropbox, etc.) or FTP them. If you contact me via the email address associated with my GitHub account, I'll send you FTP information. ~J.

**Comment by tabusaqri** [comment] 2020-07-27 10:00
Thanks @joshmoore. I sent you an email.

**Comment by tabusaqri** [comment] 2020-07-29 06:44
Hi @joshmoore,

I have uploaded the sample in the FTP server that you shared. Please check.

Regards,
Tariq Abu Saqri

**Comment by joshmoore** [comment] 2020-07-29 07:25
Transferring it now. Thanks!

**Comment by sbesson** [comment] 2020-07-29 12:27
@tabusaqri thanks for uploading your sample files. I tried to validate the data. I could not validate one the two uploaded files (`2-SER-SILU-CC-P0284-AN-01-H-02.tif`) which is corrupted as confirmed with `tiffinfo`. The second TIFF file is an OME-TIFF as the first IFD contains a valid OME-XML string. `tiffinfo` reveals the TIFF file contains 3 IFDs of size 25088x30720 with 9 SubIFDs each

- resolutions 5 through 7
<img width="900" alt="Screen Shot 2020-07-29 at 14 16 09" src="https://user-images.githubusercontent.com/1355463/88799118-47f16480-d1a6-11ea-931f-9c5664e2ef33.png"><img width="508" alt="Screen Shot 2020-07-29 at 14 16 24" src="https://user-images.githubusercontent.com/1355463/88799126-4a53be80-d1a6-11ea-82cf-cfbb19a414e2.png">
<img width="312" alt="Screen Shot 2020-07-29 at 14 16 38" src="https://user-images.githubusercontent.com/1355463/88799148-50e23600-d1a6-11ea-805a-35547fce1093.png">

- resolution 8
<img width="275" alt="Screen Shot 2020-07-29 at 14 18 25" src="https://user-images.githubusercontent.com/1355463/88799203-635c6f80-d1a6-11ea-80ff-c9fb986a1c30.png">

- resolution 9
<img width="275" alt="Screen Shot 2020-07-29 at 14 17 13" src="https://user-images.githubusercontent.com/1355463/88799165-5770ad80-d1a6-11ea-8d1d-c7184018c027.png">

It looks like resolution 8 and 9 should be defined as separate images rather than appear as sub-resolutions of the primary images. Was this issue was originally present in the original and the intermediate file that generated the OME-TIFF otherwise it might be related to an issue with `raw2ometiff`. /cc @melissalinkert

**Comment by tabusaqri** [comment] 2020-08-10 10:47
Hi @sbesson,

Sorry I was on leave.  
Shall I upload the image before the conversion to check the issue if it's from the original image?

**Comment by melissalinkert** [comment] 2020-08-12 12:29
@tabusaqri: yes, please do upload the original image.  We should then be able to easily see if the problem is with the original image, or if it is introduced during conversion.

**Comment by tabusaqri** [comment] 2020-08-13 11:57
Hi @melissalinkert: 

I uploaded the original image 284N_s1.tif for SER-SILU-CC-P0284-AN-01-H-02.tif. please check and let me know if you need anything else.

Thanks.
Tariq Abu Saqri

**Comment by melissalinkert** [comment] 2020-08-13 15:58
Thank you for uploading the original file.  If I convert it using bioformats2raw 0.2.5 and raw2ometiff 0.2.8 (the latest versions), I get an OME-TIFF file with 8 resolutions, not 10 as in ```SER-SILU-CC-P0284-AN-01-H-02.tif```.  All 8 resolutions are consistent with each other.  I can also confirm that the original file only contains one image, so it's still unclear where the 2 wrong images are coming from.

Is there any chance that multiple conversions were run with the same output file path?  That could cause strange results.  I would suggest running the conversion again with the latest bioformats2raw/raw2ometiff, making sure to specify output paths that do not already exist.  If that still doesn't work, please let us know the exact conversion commands that you are running.

**Comment by tabusaqri** [comment] 2020-08-19 07:30
Hi @melissalinkert,

I converted the same image using bioformats2raw 0.2.5 and raw2ometiff 0.2.8 (the latest versions). 

Still, the issue is the same, I got 10 resolutions like before. it seems the issue in the command which I'm using.

please find the attached script, and below is command that I'm using. 

sh omero_conversion_latest_verions.sh -f /Volumes/VB/284N_s1_2.tif -o output

[omero_conversion_latest_verions.txt](https://github.com/ome/omero-insight/files/5094610/omero_conversion_latest_verions.txt)

Thanks

**Comment by melissalinkert** [comment] 2020-08-20 20:59
Thanks for the update, @tabusaqri.  Since converting to a new output directory solves the problem, I am closing this issue.  https://github.com/glencoesoftware/bioformats2raw/pull/56 proposes to warn if the output path given to bioformats2raw already exists, which should make it easier to detect this sort of problem in the future.

**Closed by melissalinkert** 2020-08-20 20:59 UTC
