### ISSUE TITLE
settings.setStroke

### ISSUE THREAD

**Issue by pwalczysko** [ome/omero-insight#105] opened 2020-01-22 14:55 UTC
see https://github.com/ome/training-scripts/pull/76#issuecomment-577203836 - the problem is not in the script tested there, but in insight itself https://github.com/ome/training-scripts/pull/76#issuecomment-577205674

See the full output of the error in https://github.com/ome/training-scripts/pull/76#issuecomment-577202498

cc @jburel @dominikl

**Comment by dominikl** [comment] 2020-03-27 14:41
I don't get this issue...  #76 is completely unrelated to Insight, isn't it!?

**Comment by jburel** [comment] 2020-03-27 17:17
I don't get it either I think the problem is in Ilastik/Fiji plugin
Closing

**Closed by jburel** 2020-03-27 17:17 UTC
